### ISSUE TITLE
rtmp 推流到 lal，可能会 panic

### ISSUE THREAD

**Issue by universix** [q191201771/lal#116]
rtmp 推流到 lal，如果是如下的源，lal 会 panic
ffmpeg.exe -i http://:8800/hls/0/index.m3u8 -c copy -f flv rtmp://127.0.0.1:1935/live/test110

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1 pc=0x13ea02a]

goroutine 34903 [running]:
github.com/q191201771/lal/pkg/aac.(*AscContext).GetSamplingFrequency(...)
        /Volumes/extssd/chef_git/lal/pkg/aac/aac.go:160
github.com/q191201771/lal/pkg/remux.(*Rtmp2RtspRemuxer).getAudioPacker(0xc000360000, 0x6f)
        /Volumes/extssd/chef_git/lal/pkg/remux/rtmp2rtsp.go:189 +0x10a
github.com/q191201771/lal/pkg/remux.(*Rtmp2RtspRemuxer).remux(0xc000360000, 0x4, 0x800000099, 0x1, 0x0, 0xc000362000, 0x99, 0x1000)
        /Volumes/extssd/chef_git/lal/pkg/remux/rtmp2rtsp.go:161 +0x205
github.com/q191201771/lal/pkg/remux.(*Rtmp2RtspRemuxer).FeedRtmpMsg(0xc000360000, 0x4, 0x800000099, 0x1, 0x0, 0xc000362000, 0x99, 0x1000)
        /Volumes/extssd/chef_git/lal/pkg/remux/rtmp2rtsp.go:109 +0x1d1
github.com/q191201771/lal/pkg/logic.(*Group).broadcastByRtmpMsg(0xc000152000, 0x4, 0x800000099, 0x1, 0x0, 0xc000362000, 0x99, 0x1000)
        /Volumes/extssd/chef_git/lal/pkg/logic/group.go:1002 +0x1e5c
github.com/q191201771/lal/pkg/logic.(*Group).OnReadRtmpAvMsg(0xc000152000, 0x4, 0x800000099, 0x1, 0x0, 0xc000362000, 0x99, 0x1000)
        /Volumes/extssd/chef_git/lal/pkg/logic/group.go:918 +0xa5
github.com/q191201771/lal/pkg/rtmp.(*ServerSession).doMsg(0xc00032a000, 0xc00023a280, 0x99, 0x0)
        /Volumes/extssd/chef_git/lal/pkg/rtmp/server_session.go:227 +0x124
github.com/q191201771/lal/pkg/rtmp.(*ChunkComposer).RunLoop(0xc0001840a0, 0x2094c02db58, 0xc00011e2c0, 0xc00033ff00, 0xc00011e2c0, 0x0)
        /Volumes/extssd/chef_git/lal/pkg/rtmp/chunk_composer.go:240 +0x858
github.com/q191201771/lal/pkg/rtmp.(*ServerSession).runReadLoop(0xc00032a000, 0x0, 0x0)
        /Volumes/extssd/chef_git/lal/pkg/rtmp/server_session.go:185 +0xa6
github.com/q191201771/lal/pkg/rtmp.(*ServerSession).RunLoop(0xc00032a000, 0xc000181470, 0x161e060)
```

**Comment by q191201771** [comment]
已经修复，请使用master分支最新代码进行测试，感谢。

**Comment by universix** [comment]
已在 windows 下编译 master 版本重新测试，同时用 ffplay 来播放源和 lal 出来的视频流，
rtmp 推流到 lal 后：
rtsp，rtmp，httpflv，hls，httpts 拉流播放正常，且会超前于源的播放进度，卡顿基本同步（源视频播放十几秒左右会卡顿）
