### ISSUE TITLE
setting hls.enable: false with this file causes runtime error

### ISSUE THREAD

**Issue by abrar71** [q191201771/lal#136]
setting `hls.enable: false` in  the default `./conf/lalserver.conf.json` with this mp4 file causes runtime error

Use this cmd to restream the file
```
ffmpeg -stream_loop -1 -re -i frame_coutner_4k_60fps.mp4 -c copy -f flv rtmp://127.0.0.1:1935/app/123
```

File attached below

Using `run_docker.sh` for testing shows the following logs

```
2022/03/26 20:27:00.241850  WARN config file did not specify in the command line, try to load it in the usual path. - main.go:52
2022/03/26 20:27:00.241907  WARN lalserver.conf.json not exist. - main.go:68
2022/03/26 20:27:00.241944  WARN ./conf/lalserver.conf.json exist. using it as config file. - main.go:65
2022/03/26 20:27:00.243536  INFO initial log succ. - config.go:232
2022/03/26 20:27:00.243640  INFO
    __    ___    __
   / /   /   |  / /
  / /   / /| | / /
 / /___/ ___ |/ /___
/_____/_/  |_/_____/
 - config.go:235
2022/03/26 20:27:00.244242  INFO load conf file succ. filename=./conf/lalserver.conf.json, raw content={ "# doc of config": "https://pengrl.com/lal/#/ConfigBrief", "conf_version": "v0.2.9", "rtmp": { "enable": true, "addr": ":1935", "gop_num": 0, "merge_write_size": 0, "add_dummy_audio_enable": false, "add_dummy_audio_wait_audio_ms": 150 }, "default_http": { "http_listen_addr": ":8080", "https_listen_addr": ":4433", "https_cert_file": "./conf/cert.pem", "https_key_file": "./conf/key.pem" }, "httpflv": { "enable": true, "enable_https": true, "url_pattern": "/", "gop_num": 0 }, "hls": { "enable": false, "enable_https": true, "url_pattern": "/hls/", "out_path": "./lal_record/hls/", "fragment_duration_ms": 3000, "fragment_num": 6, "delete_threshold": 6, "cleanup_mode": 1, "use_memory_as_disk_flag": false }, "httpts": { "enable": true, "enable_https": true, "url_pattern": "/", "gop_num": 0 }, "rtsp": { "enable": true, "addr": ":5544" }, "record": { "enable_flv": false, "flv_out_path": "./lal_record/flv/", "enable_mpegts": false, "mpegts_out_path": "./lal_record/mpegts" }, "relay_push": { "enable": false, "addr_list":[ ] }, "relay_pull": { "enable": false, "addr": "" }, "http_api": { "enable": true, "addr": ":8083" }, "server_id": "1", "http_notify": { "enable": false, "update_interval_sec": 5, "on_server_start": "http://127.0.0.1:10101/on_server_start", "on_update": "http://127.0.0.1:10101/on_update", "on_pub_start": "http://127.0.0.1:10101/on_pub_start", "on_pub_stop": "http://127.0.0.1:10101/on_pub_stop", "on_sub_start": "http://127.0.0.1:10101/on_sub_start", "on_sub_stop": "http://127.0.0.1:10101/on_sub_stop", "on_rtmp_connect": "http://127.0.0.1:10101/on_rtmp_connect" }, "simple_auth": { "key": "q191201771", "dangerous_lal_secret": "pengrl", "pub_rtmp_enable": false, "sub_rtmp_enable": false, "sub_httpflv_enable": false, "sub_httpts_enable": false, "pub_rtsp_enable": false, "sub_rtsp_enable": false, "hls_m3u8_enable": false }, "pprof": { "enable": true, "addr": ":8084" }, "log": { "level": 1, "filename": "./logs/lalserver.log", "is_to_stdout": true, "is_rotate_daily": true, "short_file_flag": true, "timestamp_flag": true, "timestamp_with_ms_flag": true, "level_flag": true, "assert_behavior": 1 }, "debug": { "log_group_interval_sec": 30, "log_group_max_group_num": 10, "log_group_max_sub_num_per_group": 10 } }  parsed=&{ConfVersion:v0.2.9 RtmpConfig:{Enable:true Addr::1935 GopNum:0 MergeWriteSize:0 AddDummyAudioEnable:false AddDummyAudioWaitAudioMs:150} DefaultHttpConfig:{CommonHttpAddrConfig:{HttpListenAddr::8080 HttpsListenAddr::4433 HttpsCertFile:./conf/cert.pem HttpsKeyFile:./conf/key.pem}} HttpflvConfig:{CommonHttpServerConfig:{CommonHttpAddrConfig:{HttpListenAddr::8080 HttpsListenAddr::4433 HttpsCertFile:./conf/cert.pem HttpsKeyFile:./conf/key.pem} Enable:true EnableHttps:true UrlPattern:/} GopNum:0} HlsConfig:{CommonHttpServerConfig:{CommonHttpAddrConfig:{HttpListenAddr::8080 HttpsListenAddr::4433 HttpsCertFile:./conf/cert.pem HttpsKeyFile:./conf/key.pem} Enable:false EnableHttps:true UrlPattern:/hls/} UseMemoryAsDiskFlag:false MuxerConfig:{OutPath:./lal_record/hls/ FragmentDurationMs:3000 FragmentNum:6 DeleteThreshold:6 CleanupMode:1}} HttptsConfig:{CommonHttpServerConfig:{CommonHttpAddrConfig:{HttpListenAddr::8080 HttpsListenAddr::4433 HttpsCertFile:./conf/cert.pem HttpsKeyFile:./conf/key.pem} Enable:true EnableHttps:true UrlPattern:/} GopNum:0} RtspConfig:{Enable:true Addr::5544} RecordConfig:{EnableFlv:false FlvOutPath:./lal_record/flv/ EnableMpegts:false MpegtsOutPath:./lal_record/mpegts} RelayPushConfig:{Enable:false AddrList:[]} RelayPullConfig:{Enable:false Addr:} HttpApiConfig:{Enable:true Addr::8083} ServerId:1 HttpNotifyConfig:{Enable:false UpdateIntervalSec:5 OnServerStart:http://127.0.0.1:10101/on_server_start OnUpdate:http://127.0.0.1:10101/on_update OnPubStart:http://127.0.0.1:10101/on_pub_start OnPubStop:http://127.0.0.1:10101/on_pub_stop OnSubStart:http://127.0.0.1:10101/on_sub_start OnSubStop:http://127.0.0.1:10101/on_sub_stop OnRtmpConnect:http://127.0.0.1:10101/on_rtmp_connect} SimpleAuthConfig:{Key:q191201771 DangerousLalSecret:pengrl PubRtmpEnable:false SubRtmpEnable:false SubHttpflvEnable:false SubHttptsEnable:false PubRtspEnable:false SubRtspEnable:false HlsM3u8Enable:false} PprofConfig:{Enable:true Addr::8084} LogConfig:{Level:1 Filename:./logs/lalserver.log IsToStdout:true IsRotateDaily:true ShortFileFlag:true TimestampFlag:true TimestampWithMsFlag:true LevelFlag:true AssertBehavior:1} DebugConfig:{LogGroupIntervalSec:30 LogGroupMaxGroupNum:10 LogGroupMaxSubNumPerGroup:10}} - config.go:323
2022/03/26 20:27:00.244429  INFO      start: 2022-03-26 20:27:00.241 - base.go:33
2022/03/26 20:27:00.244468  INFO         wd: /lal - base.go:34
2022/03/26 20:27:00.244484  INFO       args: /lal/bin/lalserver - base.go:35
2022/03/26 20:27:00.244507  INFO    bininfo: GitTag=v0.27.1. GitCommitLog=812f9bf314b79438697a7a72ae0d9437bb485ee1 [patch] logic: 重构group. GitStatus= M conf/lalserver.conf.json | M run_docker.sh. BuildTime=2022.03.26.202626. GoVersion=go version go1.16.4 linux/amd64. runtime=linux/amd64. - base.go:36
2022/03/26 20:27:00.244550  INFO    version: lal v0.27.1 (github.com/q191201771/lal) - base.go:37
2022/03/26 20:27:00.244584  INFO     github: https://github.com/q191201771/lal - base.go:38
2022/03/26 20:27:00.244599  INFO        doc: https://pengrl.com/lal - base.go:39
2022/03/26 20:27:00.244811  INFO start web pprof listen. addr=:8084 - server_manager.go:126
2022/03/26 20:27:00.245173  INFO add http listen for httpflv. addr=:8080, pattern=/ - server_manager.go:148
2022/03/26 20:27:00.246625  INFO add https listen for httpflv. addr=:4433, pattern=/ - server_manager.go:159
2022/03/26 20:27:00.246663  INFO add http listen for httpts. addr=:8080, pattern=/ - server_manager.go:148
2022/03/26 20:27:00.246676  INFO add https listen for httpts. addr=:4433, pattern=/ - server_manager.go:159
2022/03/26 20:27:00.246686  INFO add https listen for hls. addr=:4433, pattern=/hls/ - server_manager.go:159
2022/03/26 20:27:00.246727  INFO start rtmp server listen. addr=:1935 - server.go:53
2022/03/26 20:27:00.246755  INFO start rtsp server listen. addr=:5544 - server.go:71
2022/03/26 20:27:00.246797  INFO start httpapi server listen. addr=:8083 - http_api.go:39
2022/03/26 20:27:05.382938  INFO accept a rtmp connection. remoteAddr=34.86.91.49:54314 - server.go:77
2022/03/26 20:27:05.383024 DEBUG [NAZACONN1] lifecycle new connection. net.Conn=0xc00019c010, naza.Connection=0xc0001b4000 - connection.go:192
2022/03/26 20:27:05.383079  INFO [RTMPPUBSUB1] lifecycle new rtmp ServerSession. session=0xc00019e480, remote addr=34.86.91.49:54314 - server_session.go:120
2022/03/26 20:27:05.383284 DEBUG handshake complex mode. - handshake.go:248
2022/03/26 20:27:05.383346  INFO [RTMPPUBSUB1] < R Handshake C0+C1. - server_session.go:218
2022/03/26 20:27:05.383366  INFO [RTMPPUBSUB1] > W Handshake S0+S1+S2. - server_session.go:220
2022/03/26 20:27:05.383777  INFO [RTMPPUBSUB1] < R Handshake C2. - server_session.go:228
2022/03/26 20:27:05.384019  INFO [RTMPPUBSUB1] < R connect('app'). tcUrl=rtmp://34.86.91.49:1933/app - server_session.go:383
2022/03/26 20:27:05.384061  INFO [RTMPPUBSUB1] > W Window Acknowledgement Size 5000000. - server_session.go:387
2022/03/26 20:27:05.384148  INFO [RTMPPUBSUB1] > W Set Peer Bandwidth. - server_session.go:392
2022/03/26 20:27:05.384180  INFO [RTMPPUBSUB1] > W SetChunkSize 4096. - server_session.go:397
2022/03/26 20:27:05.384210  INFO [RTMPPUBSUB1] > W _result('NetConnection.Connect.Success'). - server_session.go:402
2022/03/26 20:27:05.385025 DEBUG [RTMPPUBSUB1] read command message, ignore it. cmd=releaseStream, header={Csid:3 MsgLen:33 MsgTypeId:20 MsgStreamId:0 TimestampAbs:0}, b=len(core)=4096, rpos=25, wpos=33, hex=00000000  05 02 00 04 31 32 33 67                           |....123g|
 - server_session.go:357
2022/03/26 20:27:05.385094 DEBUG [RTMPPUBSUB1] read command message, ignore it. cmd=FCPublish, header={Csid:3 MsgLen:29 MsgTypeId:20 MsgStreamId:0 TimestampAbs:0}, b=len(core)=4096, rpos=21, wpos=29, hex=00000000  05 02 00 04 31 32 33 67                           |....123g|
 - server_session.go:357
2022/03/26 20:27:05.385116  INFO [RTMPPUBSUB1] < R createStream(). - server_session.go:414
2022/03/26 20:27:05.385128  INFO [RTMPPUBSUB1] > W _result(). - server_session.go:415
2022/03/26 20:27:05.385810 DEBUG [RTMPPUBSUB1] pubType=live - server_session.go:442
2022/03/26 20:27:05.385847  INFO [RTMPPUBSUB1] < R publish('123g') - server_session.go:443
2022/03/26 20:27:05.385873  INFO [RTMPPUBSUB1] > W onStatus('NetStream.Publish.Start'). - server_session.go:445
2022/03/26 20:27:05.386033  INFO [GROUP1] lifecycle new group. group=0xc0001e8000, appName=app, streamName=123g - group.go:112
2022/03/26 20:27:05.386100 DEBUG [GROUP1] [RTMPPUBSUB1] add rtmp pub session into group. - group__in.go:24
2022/03/26 20:27:05.386709 DEBUG [GROUP1] cache rtmp metadata. size:400 - gop_cache.go:97
2022/03/26 20:27:05.386747 DEBUG [GROUP1] cache httpflv metadata. size:403 - gop_cache.go:97
2022/03/26 20:27:05.386778 DEBUG [GROUP1] cache rtmp video seq header. size:64 - gop_cache.go:108
2022/03/26 20:27:05.386804 DEBUG [GROUP1] cache httpflv video seq header. size:67 - gop_cache.go:108
2022/03/26 20:27:05.386902 DEBUG sps={ProfileIdc:100 ConstraintSet0Flag:0 ConstraintSet1Flag:0 ConstraintSet2Flag:0 LevelIdc:52 SpsId:0 ChromaFormatIdc:1 ResidualColorTransformFlag:0 BitDepthLuma:8 BitDepthChroma:8 TransFormBypass:0 Log2MaxFrameNumMinus4:0 PicOrderCntType:0 Log2MaxPicOrderCntLsb:6 NumRefFrames:4 GapsInFrameNumValueAllowedFlag:0 PicWidthInMbsMinusOne:239 PicHeightInMapUnitsMinusOne:134 FrameMbsOnlyFlag:1 MbAdaptiveFrameFieldFlag:0 Direct8X8InferenceFlag:1 FrameCroppingFlag:0 FrameCropLeftOffset:0 FrameCropRightOffset:0 FrameCropTopOffset:0 FrameCropBottomOffset:0 SarNum:1 SarDen:1} - beta.go:41
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x77a57e]

goroutine 34 [running]:
github.com/q191201771/lal/pkg/hls.(*Muxer).FeedPatPmt(...)
        /go/src/github.com/q191201771/lal/pkg/hls/muxer.go:147
github.com/q191201771/lal/pkg/logic.(*Group).OnPatPmt(0xc0001e8000, 0xa95420, 0x178, 0x178)
        /go/src/github.com/q191201771/lal/pkg/logic/group__core_streaming.go:81 +0x5e
github.com/q191201771/lal/pkg/remux.(*Rtmp2MpegtsRemuxer).onPatPmt(0xc0001ce090, 0xa95420, 0x178, 0x178)
        /go/src/github.com/q191201771/lal/pkg/remux/rtmp2mpegts.go:134 +0x52
github.com/q191201771/lal/pkg/remux.(*rtmp2MpegtsFilter).drain(0xc0001a2190)
        /go/src/github.com/q191201771/lal/pkg/remux/rtmp2mpegts_filter_.go:96 +0x1ff
github.com/q191201771/lal/pkg/remux.(*rtmp2MpegtsFilter).Push(0xc0001a2190, 0x4, 0x800000007, 0x1, 0x0, 0xc00020a000, 0x7, 0x1000)
        /go/src/github.com/q191201771/lal/pkg/remux/rtmp2mpegts_filter_.go:81 +0x24e
github.com/q191201771/lal/pkg/remux.(*Rtmp2MpegtsRemuxer).FeedRtmpMessage(...)
        /go/src/github.com/q191201771/lal/pkg/remux/rtmp2mpegts.go:89
github.com/q191201771/lal/pkg/logic.(*Group).broadcastByRtmpMsg(0xc0001e8000, 0x4, 0x800000007, 0x1, 0x0, 0xc00020a000, 0x7, 0x1000)
        /go/src/github.com/q191201771/lal/pkg/logic/group__core_streaming.go:153 +0x2106
github.com/q191201771/lal/pkg/logic.(*Group).OnReadRtmpAvMsg(0xc0001e8000, 0x4, 0x800000007, 0x1, 0x0, 0xc00020a000, 0x7, 0x1000)
        /go/src/github.com/q191201771/lal/pkg/logic/group__core_streaming.go:39 +0x9a
github.com/q191201771/lal/pkg/rtmp.(*ServerSession).doMsg(0xc00019e480, 0xc00013d1d0, 0x7, 0x7)
        /go/src/github.com/q191201771/lal/pkg/rtmp/server_session.go:254 +0x2c7
github.com/q191201771/lal/pkg/rtmp.(*ChunkComposer).RunLoop(0xc000198120, 0x7f8870192008, 0xc0001b4000, 0xc0000c9f48, 0xc0001b4000, 0xc0001942d0)
        /go/src/github.com/q191201771/lal/pkg/rtmp/chunk_composer.go:253 +0xf13
github.com/q191201771/lal/pkg/rtmp.(*ServerSession).runReadLoop(...)
        /go/src/github.com/q191201771/lal/pkg/rtmp/server_session.go:211
github.com/q191201771/lal/pkg/rtmp.(*ServerSession).RunLoop(0xc00019e480, 0xc00013c9c0, 0x8d1b58)
        /go/src/github.com/q191201771/lal/pkg/rtmp/server_session.go:130 +0xfa
github.com/q191201771/lal/pkg/rtmp.(*Server).handleTcpConnect(0xc00013c9c0, 0x8d1b58, 0xc00019c010)
        /go/src/github.com/q191201771/lal/pkg/rtmp/server.go:79 +0x139
created by github.com/q191201771/lal/pkg/rtmp.(*Server).RunLoop
        /go/src/github.com/q191201771/lal/pkg/rtmp/server.go:63 +0x4f
```

https://user-images.githubusercontent.com/13979201/160255987-0a30ee58-138f-4514-a9d3-d6e521ee458e.mp4

**Comment by q191201771** [comment]
PR merged.
thanks.
