### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by ixugo** [q191201771/lal#342]
海康设备，国标 rtp 推流，程序 panic 结束。

以下是错误信息，求大佬指点如何修复?

`2024/02/23 11:21:50.908795 DEBUG sps={ProfileIdc:77 ConstraintSet0Flag:0 ConstraintSet1Flag:0 ConstraintSet2Flag:0 LevelIdc:42 SpsId:0 ChromaFormatIdc:1 ResidualColorTransformFlag:0 BitDepthLuma:8 BitDepthChroma:8 TransFormBypass:0 Log2MaxFrameNumMinus4:4 PicOrderCntType:0 Log2MaxPicOrderCntLsb:16 NumRefFrames:1 GapsInFrameNumValueAllowedFlag:1 PicWidthInMbsMinusOne:119 PicHeightInMapUnitsMinusOne:67 FrameMbsOnlyFlag:1 MbAdaptiveFrameFieldFlag:0 Direct8X8InferenceFlag:1 FrameCroppingFlag:1 FrameCropLeftOffset:0 FrameCropRightOffset:0 FrameCropTopOffset:0 FrameCropBottomOffset:4 SarNum:1 SarDen:1} - beta.go:41
2024/02/23 11:21:50.908872 ERROR lal: buffer too short(avc.go:540) - session.go:89
2024/02/23 11:21:50.908886 DEBUG [GROUP1] cache rtmp video seq header. size:60 - gop_cache.go:115
2024/02/23 11:21:50.908900 DEBUG [GROUP1] cache httpflv video seq header. size:59 - gop_cache.go:115
2024/02/23 11:21:52.931558 DEBUG [0x1400027c840] Buffer::Grow. move, this round need=1400, copy=88 - buffer.go:132
2024/02/23 11:21:52.934482 DEBUG sps={ProfileIdc:77 ConstraintSet0Flag:0 ConstraintSet1Flag:0 ConstraintSet2Flag:0 LevelIdc:42 SpsId:0 ChromaFormatIdc:1 ResidualColorTransformFlag:0 BitDepthLuma:8 BitDepthChroma:8 TransFormBypass:0 Log2MaxFrameNumMinus4:4 PicOrderCntType:0 Log2MaxPicOrderCntLsb:16 NumRefFrames:1 GapsInFrameNumValueAllowedFlag:1 PicWidthInMbsMinusOne:119 PicHeightInMapUnitsMinusOne:67 FrameMbsOnlyFlag:1 MbAdaptiveFrameFieldFlag:0 Direct8X8InferenceFlag:1 FrameCroppingFlag:1 FrameCropLeftOffset:0 FrameCropRightOffset:0 FrameCropTopOffset:0 FrameCropBottomOffset:4 SarNum:1 SarDen:1} - beta.go:41
2024/02/23 11:21:52.934514 ERROR lal: buffer too short(avc.go:540) - session.go:89
2024/02/23 11:21:52.934528 DEBUG [GROUP1] cache rtmp video seq header. size:60 - gop_cache.go:115
2024/02/23 11:21:52.934540 DEBUG [GROUP1] cache httpflv video seq header. size:59 - gop_cache.go:115
panic: runtime error: makeslice: len out of range

goroutine 8556 [running]:
github.com/q191201771/lal/pkg/remux.(*AvPacket2RtmpRemuxer).FeedAvPacket(0x1400080c000, {0x61, 0x17e8b60, 0x17e8b60, {0x0, 0x0, 0x0}})
	/Users/xugo/Desktop/xufan/lal/pkg/remux/avpacket2rtmp.go:303 +0x604
github.com/q191201771/lal/pkg/remux.(*AvPacket2RtmpRemuxer).OnAvPacket(0x1400080c000, {0x61, 0x17e8b60, 0x17e8b60, {0x0, 0x0, 0x0}})
	/Users/xugo/Desktop/xufan/lal/pkg/remux/avpacket2rtmp.go:80 +0x44
github.com/q191201771/lal/pkg/logic.(*Group).OnAvPacketFromPsPubSession(0x140001ae008, 0x14000188ab0)
	/Users/xugo/Desktop/xufan/lal/pkg/logic/group__core_streaming.go:105 +0x110
github.com/q191201771/lal/pkg/gb28181.(*PsUnpacker).onAvPacketWrap(0x140006222c0, 0x14000188ab0)
	/Users/xugo/Desktop/xufan/lal/pkg/gb28181/unpack.go:581 +0x210
github.com/q191201771/lal/pkg/gb28181.(*PsUnpacker).parseAvStream(0x140006222c0, 0x1c0, 0x867d0d65, {0x14000c9e00e, 0x30e, 0x100a2}, 0x4)
	/Users/xugo/Desktop/xufan/lal/pkg/gb28181/unpack.go:408 +0x628
github.com/q191201771/lal/pkg/gb28181.(*PsUnpacker).FeedRtpBody(0x140006222c0, {0x140011a600c, 0x31c, 0x31c}, 0x867d0d65)
	/Users/xugo/Desktop/xufan/lal/pkg/gb28181/unpack.go:215 +0x254
github.com/q191201771/lal/pkg/gb28181.(*PsUnpacker).FeedRtpPacket(0x140006222c0, {0x14000610000, 0x209, 0x5dc})
	/Users/xugo/Desktop/xufan/lal/pkg/gb28181/unpack.go:131 +0x3a0
github.com/q191201771/lal/pkg/gb28181.(*PubSession).feedPacket(0x140000e4600, {0x14000610000, 0x209, 0x5dc})
	/Users/xugo/Desktop/xufan/lal/pkg/gb28181/pub_session.go:241 +0x9c
github.com/q191201771/lal/pkg/gb28181.(*PubSession).runLoopUdp.func1({0x14000610000, 0x209, 0x5dc}, 0x14000188a80, {0x0, 0x0})
	/Users/xugo/Desktop/xufan/lal/pkg/gb28181/pub_session.go:192 +0xa4
github.com/q191201771/naza/pkg/nazanet.(*UdpConnection).RunLoop(0x140011fca50, 0x140000b7e88)
	/Users/xugo/go/pkg/mod/github.com/q191201771/naza@v0.30.48/pkg/nazanet/udp_connection.go:116 +0x21c
github.com/q191201771/lal/pkg/gb28181.(*PubSession).runLoopUdp(0x140000e4600)
	/Users/xugo/Desktop/xufan/lal/pkg/gb28181/pub_session.go:187 +0x88
github.com/q191201771/lal/pkg/gb28181.(*PubSession).RunLoop(0x140000e4600)
	/Users/xugo/Desktop/xufan/lal/pkg/gb28181/pub_session.go:88 +0x60
github.com/q191201771/lal/pkg/logic.(*Group).StartRtpPub.func3()
	/Users/xugo/Desktop/xufan/lal/pkg/logic/group__in.go:150 +0x34
created by github.com/q191201771/lal/pkg/logic.(*Group).StartRtpPub in goroutine 6665
	/Users/xugo/Desktop/xufan/lal/pkg/logic/group__in.go:149 +0x7c0
Process 45734 has exited with status 2
Detaching
`

**Comment by ixugo** [comment]
```
测试代码块?
```

**Comment by yzj578492228** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
